### PR TITLE
Test branch

### PR DESCRIPTION
**Pull request by artsavchenko**

### CODE REVIEW

**Comment by drerek** [comment]
Please, test before merging!

**Comment by artsavchenko** [comment]
[LPVS] Failure. There are license conflicts! 
Found licenses [Apache License 2.0]

**Comment by artsavchenko** [comment]
[LPVS] Failure. There are license conflicts! 
Found licenses [Apache License 2.0]

**Comment by artsavchenko** [comment]
[LPVS] Failure. There are license conflicts! 
Found licenses [Apache License 2.0]

**Comment by artsavchenko** [comment]
[LPVS] Failure. There are license conflicts! 
Found licenses [Apache License 2.0]

**Comment by artsavchenko** [comment]
[LPVS] Failure. There are license conflicts! 
Found licenses [Apache License 2.0]

**Comment by artsavchenko** [comment]
[LPVS] Failure. There are license conflicts! 
Found licenses [Apache License 2.0]

**Comment by artsavchenko** [comment]
[LPVS] Failure. There are license conflicts! 
Found licenses [Apache License 2.0]

**Comment by artsavchenko** [comment]
[LPVS] Failure. There are license conflicts! 
Found licenses [Apache License 2.0]

**Comment by artsavchenko** [comment]
[LPVS] Failure. There are license conflicts! 
Found licenses [Apache License 2.0]

**Comment by artsavchenko** [comment]
[LPVS] Failure. There are license conflicts! 
Found licenses [Apache License 2.0]

**Comment by artsavchenko** [comment]
[LPVS] Failure. There are license conflicts! 
Found licenses [Apache License 2.0]

**Comment by artsavchenko** [comment]
[LPVS] Failure. There are license conflicts! 
Found licenses [Apache License 2.0]

**Comment by artsavchenko** [comment]
[LPVS] Failure. There are license conflicts! 
Found licenses [Apache License 2.0]

**Comment by artsavchenko** [comment]
[LPVS] Failure. There are license conflicts! 
Found licenses [Apache License 2.0, Educational Community License v2.0]

**Comment by artsavchenko** [comment]
[LPVS] Failure. There are license conflicts! 
Found licenses [Apache License 2.0, Educational Community License v2.0]

**Comment by artsavchenko** [comment]
[LPVS] Failure. There are license conflicts! 
Found licenses [Apache License 2.0, Educational Community License v2.0]

**Pull request closed without merging**
